# Generated by Django 4.1 on 2022-08-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('directorId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('filmId', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('filmName', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('A', 'Action movies'), ('H', 'Horror'), ('D', 'Drama'), ('S', 'Sci-Fi'), ('N', 'Animation'), ('C', 'Comedy'), ('O', 'Documentary')], max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directors.director')),
            ],
        ),
    ]
